### ISSUE TITLE
Rendre possible de déploiement sur Heroku

### ISSUE THREAD

**Issue by NitriKx** [NitriKx/M2DL-IVVQ-Running-Lama#22]
Les transactions par défaut lors de la génération du controller sont en read-only.

```
2015-10-14T07:44:59.718158+00:00 app[web.1]: ERROR: cannot execute INSERT in a read-only transaction. Stacktrace follows:
2015-10-14T07:44:59.718160+00:00 app[web.1]:    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2077)
2015-10-14T07:44:59.718161+00:00 app[web.1]:    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
2015-10-14T07:44:59.718159+00:00 app[web.1]: org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2015-10-14T07:44:59.718164+00:00 app[web.1]:    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)
2015-10-14T07:44:59.718162+00:00 app[web.1]:    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:498)
2015-10-14T07:44:59.718161+00:00 app[web.1]:    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1810)
2015-10-14T07:44:59.718165+00:00 app[web.1]:    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:332)
2015-10-14T07:44:59.718165+00:00 app[web.1]:    at com.runninglama.UtilisateurDAOService.$tt__save(UtilisateurDAOService.groovy:13)
2015-10-14T07:44:59.718166+00:00 app[web.1]:    at com.runninglama.UtilisateurService.$tt__inscrireUtilisateur(UtilisateurService.groovy:40)
2015-10-14T07:44:59.718167+00:00 app[web.1]:    at com.runninglama.UtilisateurController.$tt__inscriptionPost(UtilisateurController.groovy:20)
2015-10-14T07:44:59.718167+00:00 app[web.1]:    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
2015-10-14T07:44:59.718168+00:00 app[web.1]:    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
2015-10-14T07:44:59.718169+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2015-10-14T07:44:59.718169+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2015-10-14T07:44:59.718171+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by julienCsj** [comment]
#24
