### ISSUE TITLE
Heroku - Heroku semble ne plus marcher

### ISSUE THREAD

**Issue by NitriKx** [NitriKx/M2DL-IVVQ-Running-Lama#40]
Depuis quelques temps le système déployé sur Heroku ne fonctionne plus. Il faut investigué la raison de ce problème (en utilisant le CLI heroku) et corriger le problème.

**Comment by NitriKx** [comment]
```
2015-11-11T16:07:21.754744+00:00 app[web.1]: SEVERE: The web application [] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
2015-11-11T16:07:21.720172+00:00 app[web.1]: 2015-11-11 16:07:21,719 [localhost-startStop-1] ERROR context.GrailsContextLoader  - Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'lobHandlerDetector' while setting bean property 'lobHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lobHandlerDetector': Invocation of init method failed; nested exception is org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
2015-11-11T16:07:21.720187+00:00 app[web.1]: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'lobHandlerDetector' while setting bean property 'lobHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lobHandlerDetector': Invocation of init method failed; nested exception is org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
2015-11-11T16:07:21.720188+00:00 app[web.1]:    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
2015-11-11T16:07:21.720189+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2015-11-11T16:07:21.720190+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2015-11-11T16:07:21.720191+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:745)
2015-11-11T16:07:21.720200+00:00 app[web.1]:    ... 4 more
2015-11-11T16:07:21.720211+00:00 app[web.1]: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'lobHandlerDetector' while setting bean property 'lobHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lobHandlerDetector': Invocation of init method failed; nested exception is org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
2015-11-11T16:07:21.720199+00:00 app[web.1]: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'lobHandlerDetector' while setting bean property 'lobHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lobHandlerDetector': Invocation of init method failed; nested exception is org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
2015-11-11T16:07:21.720218+00:00 app[web.1]:    ... 4 more
2015-11-11T16:07:21.720218+00:00 app[web.1]: Caused by: org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
2015-11-11T16:07:21.720212+00:00 app[web.1]:    ... 4 more
2015-11-11T16:07:21.720217+00:00 app[web.1]: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lobHandlerDetector': Invocation of init method failed; nested exception is org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
2015-11-11T16:07:21.720219+00:00 app[web.1]:    ... 4 more
2015-11-11T16:07:21.720220+00:00 app[web.1]: Caused by: org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
2015-11-11T16:07:21.720220+00:00 app[web.1]:    at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:464)
2015-11-11T16:07:21.720221+00:00 app[web.1]:    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
2015-11-11T16:07:21.720222+00:00 app[web.1]:    at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
2015-11-11T16:07:21.720222+00:00 app[web.1]:    at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
2015-11-11T16:07:21.720221+00:00 app[web.1]:    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:112)
2015-11-11T16:07:21.720223+00:00 app[web.1]:    at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24)
2015-11-11T16:07:21.720223+00:00 app[web.1]:    at org.postgresql.Driver.makeConnection(Driver.java:393)
2015-11-11T16:07:21.720224+00:00 app[web.1]:    at org.postgresql.Driver.connect(Driver.java:267)
2015-11-11T16:07:21.720224+00:00 app[web.1]:    ... 4 more
```

**Comment by NitriKx** [comment]
Vu que le JDBC est buggué, je ne vais pas passer plus de temps à essayer de le faire marche : je vais juste remettre la base H2 locale , qui sera supprimée à chaque fois que l'instance Heroku s'éteint.
